Login form
WildCodeSchool/reims-0919-js-studips pull request #15
Opened 2019-12-17 10:44 UTC by valentin519

Creation of login form

2019-12-17 10:47 UTC, wasthishelpful commented
there conflicts to resolve in App.css :/

2019-12-17 14:07 UTC, rocambille requested changes

2019-12-17 14:07 UTC, wasthishelpful commented on studips/src/component/LoginForm.js
> +    postForm (){
why not merge submitForm and postForm?

2019-12-17 14:07 UTC, rocambille commented on studips/src/component/LoginForm.js
> +    }
`document.getElementById` is not the react way: use conditional rendering instead :)

2020-01-02 10:56 UTC, rocambille requested changes

2020-01-02 10:56 UTC, wasthishelpful commented on studips/src/component/LoginForm.js
> +    const url = "http://localhost8000/user";
following REST conventions, should be http://localhost8000/users with an **s**

2020-01-02 10:56 UTC, wasthishelpful commented
conflicts to resolve in App.js ;)

2020-01-02 13:56 UTC, ghost requested changes

2020-01-02 13:56 UTC, Sheoo commented on studips/src/component/LoginForm.js
> +        this.submitForm = this.submitForm.bind(this);
submitForm is no where to be found, outdated line

2020-01-02 14:04 UTC, merged